name: chocolatine

on:
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
  push:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_coding_style:
      name: Check Coding Style
      if: github.repository != ${{ vars.MIRROR_URL }} || github.event.name == 'push'
      runs-on: ubuntu-latest
      container:
        image: ghcr.io/epitech/coding-style-checker:latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@main
        - name: run coding-style-checker.sh
          run: check.sh $(pwd) $(pwd)
        - name: looking for style errors
          run: if [ -s coding-style-reports.log ]; then while read lign; do echo "::error::$lign"; done < coding-style-reports.log; exit 2; fi

  check_program_compilation:
      name: Check Compilation
      runs-on: ubuntu-latest
      container:  epitechcontent/epitest-docker
      timeout-minutes: 2
      steps:
        - name: Checkout Repository
          uses: actions/checkout@main
        - run: make
        - run: make clean
        - run: for binary in "${{ vars.EXECUTABLES }}"; do if [ ! -x $binary ]; then exit 1; fi; done

  run_tests:
      needs: [check_program_compilation, check_coding_style]
      runs-on: ubuntu-latest
      container:  epitechcontent/epitest-docker
      timeout-minutes: 2
      steps:
        - name: Checkout Repository
          uses: actions/checkout@main
        - run: make tests_run

  push_to_mirror:
      needs: [run_tests, check_coding_style]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@main
        - run: git fetch --unshallow
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
              ${{ vars.MIRROR_URL }}
            ssh_private_key:
              ${{ secrets.GIT_SSH_PRIVATE_KEY }}
